#!/bin/bash

# stolen from http://projects.puppetlabs.com/projects/1/wiki/Puppet_Version_Control


if git rev-parse --quiet --verify HEAD > /dev/null
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Get list of new/modified manifest and template files to check (in git index)
for indexfile in $(git diff-index --diff-filter=AM --name-only --cached "$against" | egrep '\.(pp|erb|yaml)')
do
    # Don't check empty files
    if [ "$(git cat-file -s :0:"$indexfile")" -gt 0 ]
    then
        case $indexfile in
            *.pp )
                # check puppet syntax
                # A Puppet bug https://tickets.puppetlabs.com/browse/PUP-1778 prevents the 
                #use of the --ignoreimport flag.  This means that syntax-checking may not  
                # work so well with the Puppet import statement.
                ERROR_MSG=$(git cat-file blob :0:"$indexfile" | puppet parser validate --color=false 2>&1 > /dev/null) ;;
            *.erb )
                # Check ERB template syntax
                ERROR_MSG=$(git cat-file blob :0:"$indexfile" | erb -x -T - | ruby -c 2>&1 > /dev/null) ;;
            *.yaml )
                # Check yaml syntax.  Usually invoked for hiera files.
                ERROR_MSG=$(ruby -e "require 'yaml'; YAML.load_file('${indexfile}')" 2>&1 > /dev/null) ;;

        esac
        if [ "$?" -ne 0 ]
        then
            echo -n "$indexfile: $ERROR_MSG"
            exit 1
        fi
    fi
done
