#! /bin/bash

set -e
set -u
set -o pipefail


function popStash() {
    git stash pop --quiet
}

HOOK_NAME=$(basename "$0")
HOOK_SCRIPTS=($(git config --get-all "hook-envvars.$HOOK_NAME.hook-scripts"))
HOOK_SCRIPTS_DIR=$(dirname "$(readlink "$0")")

if [[ ${#HOOK_SCRIPTS[@]} -ge 0 ]]; then
    git stash --include-untracked --keep-index --quiet
    trap popStash EXIT
    for cmd in "${HOOK_SCRIPTS[@]}";
    do
        set +e
        source "$HOOK_SCRIPTS_DIR/$cmd"
        LAST_EXIT_CODE=$?
        set -e
        # Reset the trap in case the sourced script overwrote it.
        trap popStash EXIT
        if [[ $LAST_EXIT_CODE -ne 0 ]]; then
            exit 1
        fi
    done
fi
